In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, LSTM, GRU, Dense

In [2]:
# Generate sequence data
X = []
y = []
for i in range(100):
    seq = np.array([i, i+1, i+2])
    X.append(seq)
    y.append(i+3)

X = np.array(X)
y = np.array(y)

# Reshape for RNN input: [samples, timesteps, features]
X = X.reshape((X.shape[0], X.shape[1], 1))


In [6]:
X

array([[[  0],
        [  1],
        [  2]],

       [[  1],
        [  2],
        [  3]],

       [[  2],
        [  3],
        [  4]],

       [[  3],
        [  4],
        [  5]],

       [[  4],
        [  5],
        [  6]],

       [[  5],
        [  6],
        [  7]],

       [[  6],
        [  7],
        [  8]],

       [[  7],
        [  8],
        [  9]],

       [[  8],
        [  9],
        [ 10]],

       [[  9],
        [ 10],
        [ 11]],

       [[ 10],
        [ 11],
        [ 12]],

       [[ 11],
        [ 12],
        [ 13]],

       [[ 12],
        [ 13],
        [ 14]],

       [[ 13],
        [ 14],
        [ 15]],

       [[ 14],
        [ 15],
        [ 16]],

       [[ 15],
        [ 16],
        [ 17]],

       [[ 16],
        [ 17],
        [ 18]],

       [[ 17],
        [ 18],
        [ 19]],

       [[ 18],
        [ 19],
        [ 20]],

       [[ 19],
        [ 20],
        [ 21]],

       [[ 20],
        [ 21],
        [ 22]],

       [[ 21]

In [7]:
y

array([  3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100, 101, 102])

In [3]:
model_rnn = Sequential([
    SimpleRNN(10, activation='tanh', input_shape=(3, 1)),
    Dense(1)
])

model_rnn.compile(optimizer='adam', loss='mse')
model_rnn.fit(X, y, epochs=200, verbose=0)

print("RNN Prediction for [10, 11, 12]:", model_rnn.predict(np.array([[[10],[11],[12]]])))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step
RNN Prediction for [10, 11, 12]: [[9.595256]]


In [4]:
model_lstm = Sequential([
    LSTM(10, activation='tanh', input_shape=(3, 1)),
    Dense(1)
])

model_lstm.compile(optimizer='adam', loss='mse')
model_lstm.fit(X, y, epochs=200, verbose=0)

print("LSTM Prediction for [10, 11, 12]:", model_lstm.predict(np.array([[[10],[11],[12]]])))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
LSTM Prediction for [10, 11, 12]: [[12.8735075]]


In [5]:
model_gru = Sequential([
    GRU(10, activation='tanh', input_shape=(3, 1)),
    Dense(1)
])

model_gru.compile(optimizer='adam', loss='mse')
model_gru.fit(X, y, epochs=200, verbose=0)

print("GRU Prediction for [10, 11, 12]:", model_gru.predict(np.array([[[10],[11],[12]]])))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
GRU Prediction for [10, 11, 12]: [[12.9559765]]
